name: Update CV from Mega

on:
  workflow_dispatch:

jobs:
  update-cv:
    runs-on: ubuntu-latest

    # Necessary permission!
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install MEGAcmd
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y curl gnupg apt-transport-https lsb-release
          VERSION_ID=$(lsb_release -rs)
          curl -fsSL "https://mega.nz/linux/repo/xUbuntu_${VERSION_ID}/Release.key" | \
            sudo gpg --dearmor -o /usr/share/keyrings/mega-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/mega-archive-keyring.gpg] https://mega.nz/linux/repo/xUbuntu_${VERSION_ID}/ ./" | \
            sudo tee /etc/apt/sources.list.d/megacmd.list
          sudo apt-get update
          sudo apt-get install -y megacmd

      - name: Download CV files from MEGA
        run: |
          # This reliably downloads the folder into a new subdirectory
          mega-get "${{ secrets.MEGA_FOLDER }}" .

      - name: Commit and push updated CV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Find the downloaded files and move/rename them INTO the 'files' directory.
          find . -name "Academic_CV.qmd" -exec mv {} files/cv-latest.md \;
          find . -name "Academic_CV.pdf" -exec mv {} files/cv-latest.pdf \;
          
          # Add the files from their new location.
          git add files/cv-latest.md files/cv-latest.pdf
          
          git commit -m "Updated CV from Mega" || echo "No changes to commit"
          git push
