name: Update CV from Mega

on:
  workflow_dispatch:

jobs:
  update-cv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install MEGAcmd
        run: |
          sudo apt-get update
          sudo apt-get install -y megacmd

      - name: Download CV from MEGA
        run: |
          mega-login --session "${{ secrets.MEGA_SESSION_KEY }}"
          mega-get "mega:/Privat/Lebenslauf/Academic_CV.qmd" .

      - name: Commit and push updated CV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          mv "Academic_CV.qmd" content/cv.md
          git add content/cv.md
          git commit -m "Updated CV from Mega" || echo "No changes to commit"
          git push
