name: Update CV from Mega

on:
  workflow_dispatch:

jobs:
  update-cv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download and Extract MEGAcmd Binary
        run: |
          wget https://mega.nz/linux/repo/xUbuntu_24.04/amd64/megacmd_2.1.1-1.1_amd64.deb -O megacmd.deb
          mkdir megacmd-extracted
          dpkg -x megacmd.deb ./megacmd-extracted

      - name: Authenticate and Download CV
        run: |
          set -e
          MEGACMD_PATH="./megacmd-extracted/usr/bin"
          mkdir -p ~/.megaCmd

          echo "${{ secrets.MEGA_SESSION_KEY }}" > ~/.megaCmd/session

          echo "Starting MEGAcmd server..."
          nohup $MEGACMD_PATH/mega-cmd-server > ~/.megaCmd/server.log 2>&1 &

          echo "Waiting for MEGAcmd server to initialize..."
          sleep 8

          echo "Checking MEGA connection..."
          $MEGACMD_PATH/mega-cmd ls "mega:/Privat/Lebenslauf" || { echo "❌ Could not list remote directory"; cat ~/.megaCmd/server.log; exit 1; }

          echo "Downloading Academic_CV.qmd..."
          $MEGACMD_PATH/mega-cmd get "mega:/Privat/Lebenslauf/Academic_CV.qmd" . || { echo "❌ Download failed"; cat ~/.megaCmd/server.log; exit 1; }

          if [ ! -f "Academic_CV.qmd" ]; then
            echo "❌ File Academic_CV.qmd not found after download."
            cat ~/.megaCmd/server.log
            exit 1
          fi

          echo "✅ CV downloaded successfully."

      - name: Commit and push updated CV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          mv "Academic_CV.qmd" content/cv.md
          git add content/cv.md
          git commit -m "Updated CV from Mega" || echo "No changes to commit"
          git push
