name: Weekly CV Sync from Mega

on:
  schedule:
    - cron: '0 6 * * 1' # Every Monday at 06:00 UTC
  workflow_dispatch:

jobs:
  update-cv:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Allows the GITHUB_TOKEN to push to the repository

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download CV directly from Mega using rclone
        run: |
          echo "Syncing CV from Mega account with 2FA..."
          rclone copy \
            --mega-user "${{ secrets.MEGA_USER }}" \
            --mega-pass "${{ env.RCLONE_CONFIG_PASS_PASS }}" \
            --mega-2fa-key "${{ secrets.MEGA_TOTP_KEY }}" \
            mega:"Privat/Lebenslauf/Academic_CV.qmd" . # <-- IMPORTANT: Change this to your file's path in Mega
        env:
          RCLONE_CONFIG_PASS_PASS: ${{ secrets.MEGA_PASS }}

      - name: Overwrite existing CV
        run: |
          mkdir -p ./files
          mv cv-latest.md ./files/cv-latest.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ./files/cv-latest.md
          
          if git diff-index --quiet HEAD; then
            echo "No changes detected. CV is already up-to-date."
          else
            echo "CV has been updated. Committing and pushing..."
            git commit -m "Update CV from Mega.nz"
            # V-- THE PUSH COMMAND IS NOW MUCH SIMPLER --V
            git push
          fi
