name: Update CV from Mega

on:
  workflow_dispatch:

jobs:
  update-cv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install MEGAcmd
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y curl gnupg apt-transport-https
          curl -fsSL https://mega.nz/linux/repo/xUbuntu_24.04/Release.key | \
            sudo gpg --dearmor -o /usr/share/keyrings/mega-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/mega-archive-keyring.gpg] https://mega.nz/linux/repo/xUbuntu_24.04/ ./" | \
            sudo tee /etc/apt/sources.list.d/megacmd.list
          sudo apt-get update
          sudo apt-get install -y megacmd

      - name: Download CV from MEGA
        run: |
          mega-login --session "${{ secrets.MEGA_SESSION_KEY }}"
          mega-get "mega:/Privat/Lebenslauf/Academic_CV.qmd" .

      - name: Commit and push updated CV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          mv "Academic_CV.qmd" content/cv.md
          git add content/cv.md
          git commit -m "Updated CV from Mega" || echo "No changes to commit"
          git push
