name: Update CV from Mega

on:
  workflow_dispatch:

jobs:
  update-cv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install rclone
        run: |
          sudo apt-get update
          sudo apt-get install -y rclone

      - name: Download CV directly from Mega using rclone
        run: |
          echo "Syncing CV from Mega account..."
          rclone copy "mega:Privat/Lebenslauf/Academic_CV.qmd" cv-latest.md
        env:
          RCLONE_CONFIG_MEGA_TYPE: mega
          RCLONE_CONFIG_MEGA_USER: ${{ secrets.MEGA_USER }}
          RCLONE_CONFIG_MEGA_PASS: ${{ secrets.MEGA_PASS }}

      - name: Commit and push updated CV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          mv cv-latest.md content/cv.md
          git add content/cv.md
          git commit -m "Updated CV from Mega" || echo "No changes to commit"
          git push
